sonar.host.url=http://localhost:9000
sonar.projectKey=ecommerce-web
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.typescript.lcov.reportPaths=coverage/ecommerce-ui/lcov.info
