sonar.host.url=https://sonarcloud.io
sonar.organization=iignaasii47
sonar.projectKey=iignaasii47_E-Commerce-App
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.typescript.lcov.reportPaths=coverage/ecommerce-ui/lcov.info
