sonar.host.url=http://localhost:9000
sonar.token=squ_50750bb1b22c7019db867d3718fba12ad1d7381c
sonar.projectKey=ecommerce-web
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.typescript.lcov.reportPaths=coverage/ecommerce-ui/lcov.info
